[project]
name = "timer-sentinel"
version = "0.1.0"
description = ""
authors = [
    {name = "aaron",email = "aaron@aaron.es"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "timer_sentinel", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
